### ISSUE TITLE
[Question] How to use withViewport with withRouter ?

### ISSUE THREAD

**Issue by rockmandash** [streamich/libreact#16]
Hello, thank you for this amazing library.
I have a component like this
```javascript
export default withViewport(MyComponent, 'visible', {
  threshold: 0.25
});
```
Normaly with HOCs I will do this
```javascript
export default compose(withViewport, withRouter)(MyComponent)
```
But I have `threshold` parameters!
How do I pass in?
Thank you!

**Comment by streamich** [comment]
You can wrap the `withViewport` HOC into your custom one.

```js
const withMyViewport = (Comp) => withViewport(Comp, 'visible', {threshold: 0.25});
```

And then use your new HOC.

```js
export default compose(withMyViewport, withRouter)(MyComponent)
```

Hope that woks.

**Comment by rockmandash** [comment]
@streamich for your reply!
