### ISSUE TITLE
[question] how to consume libreact in TypeScript

### ISSUE THREAD

**Issue by ricardocasares** [streamich/libreact#9]
Hi there! Thanks for this awesome library!
I might be missing something as when I try to import for example, router components, I'm getting:

`Cannot find declaration file for module...`

<img width="434" alt="screen shot 2018-08-13 at 8 15 52 pm" src="https://user-images.githubusercontent.com/84963/44049914-b9f9ad6c-9f35-11e8-8241-557bb9f99eda.png">

When importing from `src` instead of `lib` I don't get this error, but `parcel-bundler` can't find the sources.

Any suggestions?

Cheers!

**Comment by streamich** [comment]
Unfortunately, currently TypeScript types are not exported, somebody has to enable `"decalration": true` in [this config](https://github.com/streamich/libreact/blob/master/tsconfig.json#L3-L21) and make sure it works well.

**Comment by streamich** [comment]
Cool, thanks!
